### ISSUE TITLE
POI检索位置不对

### ISSUE THREAD

**Issue by freedom1991** [baidumapapi/wxapp-jsapi#10]
用web版百度地图和小程序版百度地图搜索同一个位置，返回的地理坐标不一致

**Comment by memoryyang** [comment]
默认返回的坐标系是gcj02的，要转换成百度的坐标系

**Comment by dandandancj** [comment]
因为小程序只能用腾讯地图，所以接口返回的都是gcj02的坐标~
百度地图使用的是bd09
