### ISSUE TITLE
地址信息转换为经纬度

### ISSUE THREAD

**Issue by codon19** [baidumapapi/wxapp-jsapi#12]
大佬，有将具体的收货地址转换为经纬度的方法？

**Comment by pcjgithub** [comment]
这个我遇到了，但是调用小程序的api获取的经纬度不是特别精确，和PC在浏览器端有0.008度左右的差距

**Comment by FloraCat526** [comment]
小程序里的地图显示是腾讯地图，使用的是gcj02坐标系；PC上如果使用的百度地图JSAPI的坐标系是bd09坐标系，是两个坐标系之间的差距，进行一下坐标系转换就可以。
