### ISSUE TITLE
请问有为小程序开发瓦片功能吗？

### ISSUE THREAD

**Issue by xutianh** [baidumapapi/wxapp-jsapi#16]
你好项目需要在小程序中使用瓦片，但是在API中没有找到，以后会有增加吗？

**Comment by mengxin-FE** [comment]
同问小程序可以用瓦片API吗，另外请问小程序可以用JSAPI吗？ 主要和微信小程序JSAPI 区别是什么呢？

**Comment by mengxin-FE** [comment]
> 你好项目需要在小程序中使用瓦片，但是在API中没有找到，以后会有增加吗？

请问你做出来了吗？小程序可以用瓦片了吗

**Comment by mengxin-FE** [comment]
请问小程序有瓦片API了吗？ 可以用JS API吗？  小程序JSAPI和JSAPI区别在哪呢？可以混用吗

**Comment by xutianh** [comment]
> > 你好项目需要在小程序中使用瓦片，但是在API中没有找到，以后会有增加吗？
> 
> 请问你做出来了吗？小程序可以用瓦片了吗
我都已经不做小程序了😂

**Comment by FloraCat526** [comment]
> 请问小程序有瓦片API了吗？ 可以用JS API吗？ 小程序JSAPI和JSAPI区别在哪呢？可以混用吗

小程序JSAPI只支持lbs数据服务，不支持地图渲染能力。想在小程序上使用地图展示，一种方案可以直接使用小程序自身的地图服务叠加这个小程序提供的lbs数据服务，或使用百度地图JSAPI以webView方式嵌入到小程序中。
