### ISSUE TITLE
APP不存在，AK有误请检查再重试

### ISSUE THREAD

**Issue by FlyArtist** [baidumapapi/wxapp-jsapi#20]
创建的小程序应用，在小程序端调用天气API显示“APP不存在，AK有误请检查再重试”，多次检查AK均无问题

**Comment by z138141855** [comment]
同上

**Comment by songloveyuan** [comment]
解决办法是再申请一个新的ak

**Comment by FloraCat526** [comment]
由于进行ak鉴权分端控制，小程序端jsapi暂不支持天气服务，可以通过webAPI天气服务(https://lbsyun.baidu.com/index.php?title=webapi/weather)调用。
