### ISSUE TITLE
小程序返回的经纬度和PC调用返回的经纬度不同，同样的地址

### ISSUE THREAD

**Issue by pcjgithub** [baidumapapi/wxapp-jsapi#21]
我调用了小程序专用的百度api，输入一个字符串，发现了实际返回的经纬度和在pc调用的有一些差异，所以能不能给解决一下；
例子：北京市天安门广场人民英雄纪念碑
PC的api返回的 116.404043,39.911012
小程序的api返回的 lat: 39.904667375497, lng: 116.39766663332
烦请各位高手支招

**Comment by smileyby** [comment]
我也遇到了这个问题，提工单完全没人回复一度怀疑百度地图是不是解散了

**Comment by FloraCat526** [comment]
小程序里的地图显示是腾讯地图，使用的是gcj02坐标系；PC上如果使用的百度地图JSAPI的坐标系是bd09坐标系，是两个坐标系之间的差距，进行一下坐标系转换就可以。
