### ISSUE TITLE
微信地图API是否支持聚散图?

### ISSUE THREAD

**Issue by eguid** [baidumapapi/wxapp-jsapi#22]
比如js-API里面的聚散图效果，也叫点聚合

**Comment by FloraCat526** [comment]
1、小程序JSAPI只提供LBS数据服务，如果使用的是小程序自身的地图，建议查看一下腾讯地图官网看下是否有聚散图。
2、如果使用的百度地图JSAPI嵌入到小程序中，2d地图可以看下这个：https://github.com/huiyan-fe/BMap-JavaScript-library；3D地图可以看下这个：https://mapv.baidu.com/gl/examples/editor.html#point-cluster.html
