### ISSUE TITLE
天气查询数据问题。

### ISSUE THREAD

**Issue by chenjiacong** [baidumapapi/wxapp-jsapi#25]
使用天气查询文件类， var weatherData = data.currentWeather[0];返回的竟然是前几天的天气数据。返回的originalData数组更奇葩，前四五天的数据到今天。是时间返回有问题，还是数据本身就是前几天的天气预报？

**Comment by lxn07122945** [comment]
原来接入的天气服务因为没人维护下线了，目前正在讨论新的解决方案。预计十一之后会对天气服务进行一下升级

**Comment by xiangnini** [comment]
也遇到同样的问题,数据是十几天的.

**Comment by vanilla110** [comment]
传入经纬度，部分地区会获取不到数据，接口回调fail，错误信息：statusCode: "No result available"

**Comment by butters001** [comment]
"No result available"    北京的天气都查不出来吗 是不是代码里的接口没更新？

**Comment by qqccyv** [comment]
十一之后还是全部都是老数据

**Comment by hzxulin** [comment]
date: "2020-12-22"
error: -3
status: "No result available"

**Comment by LitChi666** [comment]
> 日期：“ 2020-12-22”
> 错误：-3
> 状态：“无可用结果”
解决了吗

**Comment by xiaolin0088** [comment]
有点小坑，好多人"No result available"的嘛

**Comment by FloraCat526** [comment]
由于进行ak鉴权分端控制，小程序端jsapi暂不支持天气服务，可以通过webAPI天气服务(https://lbsyun.baidu.com/index.php?title=webapi/weather)调用。
