### ISSUE TITLE
为什么我的页面刷出来的是“腾讯地图”？

### ISSUE THREAD

**Issue by ZhouYL0213** [baidumapapi/wxapp-jsapi#5]
![image](https://cloud.githubusercontent.com/assets/18501666/25744086/94fa9758-31ca-11e7-9e68-6c6b1211fbd1.png)

您好！ 我加载了这个demo，换上我在百度申请的api，为什么显示的是“腾讯地图”啊

**Comment by dandandancj** [comment]
微信小程序不允许开发者使用其他厂商的地图的。。所以目前我们的小程序JSAPI提供的是数据相关的服务，底图的服务因为微信小程序的限制无法支持

**Comment by anranxinghai** [comment]
这个意思，是不是我用了百度的数据，仍然需要把百度的数据，转换为腾讯的坐标？

**Comment by dandandancj** [comment]
接口里面可以在调用我们的api的时候配置是否返回腾讯的坐标~如果配置了的话，就不用自己写逻辑再转换了
